### ISSUE TITLE
Add an option to reset synchronisation

### ISSUE THREAD

**Issue by Ygster** [pmartin/plop-reader#53]
In case of trouble or strange behavior, it could be interesting to have an option to empty the local database of plop reader or to reset synchronization to return to the state of wallabag.

In my case (related to #52), I have deleted an entry in wallabag and as the article was stayed in plop reader, I have archived it. Now the synchronization doesn't work anymore because of the state as this entry, so it would be interesting to reset the synchronisation.

**Comment by Ygster** [comment]
In a first time, it could only be an option that launch the removal of the database.sqlite3 file and the entries directory (i have manually tested that and it works).

**Comment by pmartin** [comment]
Hi, Thanks for the issue ;-)
I like this idea and agree it could be useful in some cases like yours (or others, actually) ; I'll probably add some "advanced" sub-menu (with a "reset everything" entry in it) in the application's menu.

**Comment by pmartin** [comment]
Hi @Ygster 

This feature has just been implemented.
I am not doing a releasing for this => it will be available in the next release (either 0.3.x or 0.4)

Thanks again for the idea!
