### ISSUE TITLE
Unable to sync after upgrade to v0.3.0

### ISSUE THREAD

**Issue by Ygster** [pmartin/plop-reader#61]
After replacing the app by the version 0.3.0 on the ereader, it was unable to synchronise and finished with an error.
The error was,
"Exception: Could not create OAuth token: server returned a 500 status code."

After deletion of database file and entries directory, the sync complete successfully.

If that help, I have update wallabag from version 2.1.1 to version 2.1.3 in the same time I upgrade plop reader.

**Comment by pmartin** [comment]
Hi,

Thanks for this report; I'll try reproducing it during my next upgrade of wallabag, to see if I can find something messed up on the application's side, that could explain this behavior (like sending invalid data to the server).

In the meantime, do you have access to more logs on the server-side, that could give more information about the 500 error (as this code corresponds to an error on the server)?
You might be able to get something in your apache/nginx logs, on in php error log, with a bit of luck...

Thanks again :-)

Oh, and I've just raised the priority of #53 (Add an option to reset synchronisation), which would help in this kind of situation ;-)

**Comment by Ygster** [comment]
Hello,

I checked but don't see any 500 errors in the logs on the server (I have some others problems on the server with PostgreSQL applications since I upgrade pgsql to 9.4, it may be related).

Thanks.

**Comment by Ygster** [comment]
Finally it was from my side (problem between chair and keyboard ;-)
Close the issue
